---
title: Publications of My Classmates
author: tc
date: '2017-07-28'
slug: publications-of-my-classmates
categories:
  - trivial
  - notes
tags:
  - bibliography

bibliography: "references.bib"
csl: pnas.csl
---

> "Explain it like I'm five"

For a starter, it might be interesting to see what my classmates (undergrad period) are doing with their research, and try to explain it with my shameless, shallow, short-sighted, lack-of-common-sense point of view.



***

1. *Natural selection can favor the evolution of ratchet robustness over evolution of mutational robustness* [@lan_natural_2017]
    - I read about the abstract and didn't get it. What's Muller's ratchet and epistasis?
    
***

2. *Resting-state functional connectivity between the dorsal anterior cingulate cortex and thalamus is associated with risky decision-making in nicotine addicts* [@wei_resting-state_2016]
    - Conclusion: people smoke more tends to make bold moves. they used fMRI to show that bold moves are associated with 
        - heavy smoker
        - stronger connectivity between some brain areas
    - What is "risk level-related activation"?

***

3. *Simulating Large-Scale Conformational Changes of Proteins by Accelerating Collective Motions Obtained from Principal Component Analysis* [@peng_simulating_2014]
    - Molecular dynamics, great...
    - So it uses modes found in PCA to guide structural sampling, which solves some kind of bias called "tip effect" in the elastic models.
    
***



# Reference

