---
title: write blog with blogdown
author: TC
date: '2017-07-12'
slug: write-blog-with-blogdown
categories:
  - trivial
tags:
  - r-markdown
  - notes
  - blogdown
---

> Long live rmarkdown

## One Document to Rule Them All

I have to admit that writing in rmarkdown feels luxurious. It's like a little toy that I cherish and can't wait to share ~~and show off~~ in front of other buddies.

It has [simple grammars which can be mastered in 10 minutes](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) and [kicking-ass outputs](http://rmarkdown.rstudio.com/gallery.html), which achieved a balance between simplicity and functionality that I have long dreamed of. I can't be more happier moving from MS echosystem to rmarkdown.

Github is another thing I find interesting and useful. Version control is one thing, the door to the open source world full of excitings is another^[I mostly play with lots of #Rstat packages].

And it's getting better! Besides writing a experiment log, creating a ppt, writing a book and writing a thesis, now it's even possible to maintain a personal blog! 

By combining blogdown,github and netlify, it's possible to write a blog in rstudio by exploiting rich format controls in rmarkdown, then push it to github, and netlify synchronizes the blog site with your repo in a neat and satisfying way! 

Now I can save more time for [being lazy](/post/2017/07/11/time-management/)

## Summary

In the era of information, BBS and blog sites seems to have faded away, been replaced by social networks, which are full of short, fragmented information tailored for fast-paced lifestyles. But I don't care. I like this little toy named blogdown, I know it'll benefit me in the future.

Then I did it, and I'll maintain my little blog for myself.

***

I saw plenty of [Blogdown](https://bookdown.org/yihui/blogdown/) tutorials around. Maybe I'll do mine while I'm more familiar with how to play with it.
