---
title: Track changes in rmarkdown written reports
author: tc
date: '2017-07-28'
slug: track-changes-in-rmarkdown
categories:
  - trivial
tags:
  - r-markdown
---

## Hmmm

During the process of writing the report with the help of my supervisor, it is frequently required for several rounds of revision, such as the following scenario:

- I write the first version in Rmarkdown, compiled in pdf  
- I send PDF to my supervisor  
- He makes changes and send it back to me   
- I make changes again, compile a new pdf and send it back

He is like (-_-)#, because there's no track-change for my new made changes in pdfs

## Trackchange is important

I use git for the version control during writing but my supervisor don't, neither rmarkdown.

I have planned to suggest him to use github's `history` to track changes, after some digging, I think its experience is worse than that of track-change in word. I find it not worth recommending at all. Although the github history can view different changes in a lot of ways, but none of them are satisfyingly good enough for collaborative editing documents where track-change is a must: 

- Rmarkdown source files doesn't have figures or tables. The experience of reading a source markdown file is like -_- ^[Although the / in latex is much worse IMO]

For the diff function in github/rstudio is not good enough:

- It's not intuitive or user friendly. and you have to have a github account!

- `history-unified/split`: whole paragraph is shown. Because they are lengthy, one can't find the "actual" changes made ^[Such as a single lowercase -> uppercase]. This maybe useful in coding but useless in tracking changes in documents. And the comment or specific lines? useless as well.

- `display the rich-diff`: changes are displayed nicely. However: 
    - It doesn't have the comment feature (even though it's bad)
    - It may fail sometimes, showing "nahh we can't diff this for ya". 

In summary the version control of git is really a bad idea for track-changes for documents. 

## Solutions

1. Tell my supervisor to pickup rmarkdown, & github, and send him the sourcefile.  
    - I don't think forcing my supervisor to learn git or rmarkdown and all the fancy stuff is a good idea.

2. Rmarkdown can knit to word
    - after changes are made to the word, you have to work on the word after the first round, so what's the purpose?

3. I WILL FALL BACK into the abyss of word.

***


***
