---
title: Configuring blog test
author: tc
date: '2017-07-26'
slug: configuring-blog-test
categories:
  - trivial
tags:
  - blogdown
output:
  blogdown::html_page:
    toc: true
    number_sections: true
draft: true
---

# Add TOC

***

## title1

### title 1.1

## title2

### title 2.1

#### title 2.1.1

***

code for toc and titles is in plain markdown:

```
YAML:

---
title: Configuring blog test
author: tc
date: '2017-07-26'
slug: configuring-blog-test
categories:
  - trivial
tags:
  - blogdown
output:
  blogdown::html_page:
    toc: true
---

markdown style title:

## title1

### title 1.1

## title2

### title 2.1

#### title 2.1.1
```

***

# enable disqus 

[Following this PR](https://github.com/yihui/hugo-xmin/pull/4)

- Well, it seems that editing things in the /themes/hugo-xmin/exampleSite/ doesn't work

- ok i find it, config.toml is in the home dir /blogsite/config.toml

- edited `config.toml` and `layouts/partials/foot_custom.html` as in PR:

> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

- follow the [troubleshooting guide](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22):
        - add `netlify.com` in the trusted domain doesn't work  
        - double check shortname: correct in config.toml  
        - "recent webhost or domain name change"? no.  
        - "timeout" : unclear  
        - HTTP status error: unclear  
        - non-ASCII characters: not any  
        - incorrectly formatted javascript variables: unclear, used _internal
         
## update `r Sys.time()`

It is somehow working, but I don't know why because of limited knowledge in the hugo frame work (and overall website setups)

- Here is what I've tried, one of them might work:
    - add "rbind.io" in trusted domain in disqus
    - use `HUGO_VERSION 0.25.1` in netlify deploying specification (previous: 0.24.1 and local:0.20.1 seems to be outdated)
    - strictly follow [this PR](https://github.com/yihui/hugo-xmin/pull/4)
    
Next step is to make blogtest2 working, which is [here](http://testtc.netlify.com/)

## update `r Sys.time()`

playing with the testblog

Here is what I found:

two disqus names: 
    a. tcblogsitetest  
    a. tc_testit
    
two blogsites:
    1. http://testtc.netlify.com/
    1. http://tc.rbind.io/
    
test:
    - a + 1, a + 2, working
    - b + 1, b + 2, notworking
    - settings of a,b: besides shortname, there is no difference: they set netlify.com and rbind.io to trusted domain in advanced search.

A preliminary conclusion is that problem is in disqus set up, not hugo (or blogdown).


## update `r Sys.time()` Finally!!!

It is working for both disqus shortnames, great.





