---
title: "About Cancer"
author: "TC"
date: '2017-07-13'
categories: 
  - cancer
slug: about-cancer
tags: 
  - cancer
bibliography: /home/tc/GIT/blogsite/references.bib
draft: true
---

### "This blog gives me cancer"

I am working on a small project related to cancer now. 

Before I started my project in this lab, my only impression on cancer is that it's only a nasty disease. A nasty, deadly disease that's difficult to cure and difficult to predict as well. 

But as I've read further, it appears more than that. 

I'll write some random ideas during reading the cancer literature that I find interesting, or hillarious, or thought-provoking, or we have no idea. 

***

#### This is going to be a list in an arbitrary order

- From the perspective of evolution, cancer cells is trying to survive from senescence by growing like crazy. They know you are getting old and don't have much time left, so they proliferate for a better chance of survival. 

- Sequencing the whole genome doesn't (usually) tell you why you get cancer (as of today in `r Sys.Date()`), because cancer genome is full of noise, which is caused by accumulated mutations from age and successive disruptions in the DNA repair mechanisms.

- Data indicates that developed countries have higher incident rates of cancer than developing countries. An appealing explanation is that people in developing countries do not live long enough to the stage when cancer is a major concern.

- Cancer stem cell hypothesis, an appealing model that assumes that cancers originate from a tiny subset of cells with stemness. Following this notion, one strategy would be find out these CSCs and kill them. Well, it cannot.

- Cancer cells mainly use glycolysis in energy metabolism even if there's enough oxygen, referred as warburg effect.


- Is there a reason, or biological purpose, for cancer?
    - "If we live old enough, all of us will get cancer eventually."
    
